language: rust
rust:
  - nightly
sudo: false
cache: cargo

before_script:
- rustup component add rustfmt
script:
  - bash ./.travis.build.sh

deploy:
  provider: releases
  token: "${RELEASES_TOKEN}"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true

